version: '3.8'
services:
    # mysql service
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_DATABASE=desarrollo
            - MYSQL_USER=desarrollo
            - MYSQL_PASSWORD=test
        ports:
            - 3306:3306
        volumes:
            - ./schemas/:/var/lib/mysql

    # php7.4 Service
    php:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: php
        restart: always
        tty: true
        ports:
            - 9000:9000
        # environment:
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql

    # Nginx Service
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: always
        tty: true
        ports:
            - '80:80'
        volumes:
            - ./:/var/www/html
            - ./nginx.conf/:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql

    # phpmyadmin service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        environment:
            - PMA_HOST=mysql
            - PMA_PORT="3306"
            - PMA_USER=desarrollo
            - PMA_PASSWORD=test
        ports:
            - 8080:80
        depends_on:
            - mysql

volumes:
    code: {}
    schemes: {}
